using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
/// <summary>
/// 0.1ï¿½bï¿½ï¿½ï¿½Æ‚Éuï¿½ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½)ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½*ï¿½ï¿½Éoï¿½Ä‚ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½*ï¿½Jï¿½pï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½vï¿½Åƒnï¿½[ï¿½gï¿½ğ‘‚â‚·
/// </summary>
public class AddHeart : MonoBehaviour
{
    [SerializeField] Text _heartUI;
    [SerializeField] HeartShop _heartShop;
    /// <summary> ï¿½nï¿½[ï¿½gï¿½Ì‘ï¿½ï¿½ï¿½ </summary>
    public float _heart = 50;

    /// <summary>0.1ï¿½bï¿½Ô‚Å‘ï¿½ï¿½ï¿½ï¿½ï¿½nï¿½[ï¿½gï¿½Ìï¿½</summary>
    [SerializeField] public int _addHearts;

    float _timer;

    //0.1ï¿½bï¿½Ô‚Éˆï¿½ñ‘‚â‚·
    [SerializeField] float _addHeartTime = 0.1f;
    
    //ï¿½ï¿½É‚ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½fï¿½Bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½mï¿½[ï¿½}ï¿½ï¿½ï¿½ÈƒLï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½
    int _normalConditionPlayerCount = 0;

    //ï¿½ï¿½É‚ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½fï¿½Bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½nï¿½bï¿½sï¿½[ï¿½ÈƒLï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½
    int _happyConditionPlayerCount = 0;

    //Hungryï¿½Ìï¿½ï¿½vï¿½l
    int _hungryTotalValue;
    
    //Happyï¿½Ìï¿½ï¿½vï¿½l
    int _happyTotalValue;
    
    //Smartï¿½Ìï¿½ï¿½vï¿½l
    int _smartTotalValue;
    
    //Familiarityï¿½Ìï¿½ï¿½vï¿½l
    int _familiarityTotalValue;

    void Update()
    {   
        _timer += Time.deltaTime;
        if (_addHeartTime < _timer)
        {
            foreach (var charctor in LevelManager.HomeCharactorList)
            {
                //_normalConditionPlayerCountï¿½ÉAï¿½ï¿½É‚ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½fï¿½Bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½mï¿½[ï¿½}ï¿½ï¿½ï¿½ÈƒLï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                if (charctor.PlayerCondition.Value == Condition.Normal)
                {
                    _normalConditionPlayerCount++;
                }
                //ï¿½ï¿½É‚ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½Ìï¿½ï¿½vï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                _hungryTotalValue += charctor.Hungry;
                _happyTotalValue += charctor.Happy;
                _smartTotalValue += charctor.Smart;
                _familiarityTotalValue += charctor.Familiarity;
            }

            _addHearts =
                //1 + (ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½/10)
                (LevelManager.AllCharactorList.Count / 5)

                //ï¿½~1 + (ï¿½ï¿½É‚ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½fï¿½Bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½mï¿½[ï¿½}ï¿½ï¿½ï¿½ÈƒLï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½/10)
                * _normalConditionPlayerCount

                //ï¿½~1 + (ï¿½ï¿½É‚ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½Ìï¿½ï¿½vï¿½l/100)
                * ((_hungryTotalValue + _happyTotalValue + _smartTotalValue + _familiarityTotalValue + 1) / 750)

                //ï¿½~1 + (ï¿½ï¿½ï¿½ï¿½ï¿½Èƒpï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½xï¿½ï¿½/100)
                * _heartShop._friendPowerLevel;

            //ï¿½ï¿½@_addHearts = 1.6 * 1.0 * 1.5 * 1.90 * 1.01 

            //ï¿½nï¿½[ï¿½gï¿½Ì‘ï¿½ï¿½ï¿½+=0.1ï¿½bï¿½Ô‚Å‘ï¿½ï¿½ï¿½ï¿½ï¿½nï¿½[ï¿½gï¿½Ì—ï¿½
            _heart += _addHearts;

            //ï¿½ï¿½ï¿½lï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
            _normalConditionPlayerCount = 0;
            _hungryTotalValue = 0;
            _happyTotalValue = 0;
            _smartTotalValue = 0;
            _familiarityTotalValue = 0;

            //ï¿½^ï¿½Cï¿½}ï¿½[ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
            _timer = 0;
        }
        int IntHeart = (int)_heart;
        _heartUI.text = IntHeart.ToString();
    }
    /// <summary>countï¿½ï¿½1.(int count)ï¿½Å•Ô‚ï¿½ </summary>
    /// <param name="count"></param>
    /// <returns></returns>
    float meg(int count)
    {
        return 1 + (float)count / 10.0f;
    }

    float meg01(int count)
    {
        return 1 + (float)count / 100.0f;
    }

}
