using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class HeartShop : MonoBehaviour
{
    /// <summary>TEXTï¿½ÉƒRï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½Æ‚ï¿½ï¿½Ä•tï¿½ï¿½ï¿½Ä‚ï¿½</summary>
    [SerializeField] AddHeart _addHeart;

    [SerializeField] Text _addHeartSeconds;
    [SerializeField] Text _touchAddHeart;
    [SerializeField] Text _heartCost0;
    [SerializeField] Text _heartCost1;

    [SerializeField] Button[] _shopButton;

    /// <summary> ï¿½ï¿½ï¿½ï¿½ï¿½Èƒpï¿½ï¿½ï¿½[ï¿½Ìƒï¿½ï¿½xï¿½ï¿½ï¿½@ï¿½ï¿½ï¿½bï¿½Ô‚ï¿½ï¿½ï¿½ï¿½Èƒpï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½~ï¿½Pï¿½Oï¿½Ìƒnï¿½[ï¿½gï¿½ï¿½ï¿½Qï¿½bï¿½g </summary>
    public int _friendPowerLevel = 1;
    /// <summary> ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½Iï¿½[ï¿½ï¿½ï¿½Ìƒï¿½ï¿½xï¿½ï¿½ï¿½@ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ü‚ï¿½ï¿½Iï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½É‰ï¿½ï¿½ï¿½ï¿½Äƒnï¿½[ï¿½gï¿½ï¿½ï¿½Qï¿½bï¿½g </summary>
    public int _lovePowerLevel = 1;

    //ï¿½Rï¿½Xï¿½gï¿½{ï¿½ï¿½ï¿½iï¿½ï¿½ï¿½j
    int _level = 500;

    public int _strokingAddHeart = 10000;

    void Start()
    {
        Application.targetFrameRate = 60;
        _heartCost0.text = (_level * _friendPowerLevel).ToString();
        _addHeartSeconds.text = (_addHeart._addHearts * 10).ToString("F0") + "/s";
        _heartCost1.text = (_level * _lovePowerLevel).ToString();
        _touchAddHeart.text = (_strokingAddHeart).ToString();
    }

    void FixedUpdate()
    {
        if (1000000 < _addHeart._addHearts * 10)
        {
            int kilo = (int)(_addHeart._addHearts * 10) / 1000000;
            _addHeartSeconds.text = kilo + "m/s";
        }
        else if (1000 < _addHeart._addHearts * 10)
        {
            int kilo = (int)(_addHeart._addHearts * 10) / 1000;
            _addHeartSeconds.text = kilo + "k/s";
        }
        else
        {
            _addHeartSeconds.text = ((int)(_addHeart._addHearts * 10)).ToString() + "/s";
        }
        foreach (var button in _shopButton)
        {
            button.interactable = false;
        }
        if (_addHeart._heart > _level * _friendPowerLevel)
        {
            _shopButton[0].interactable = true;
        }
        if (_addHeart._heart > _level * _lovePowerLevel)
        {
            _shopButton[1].interactable = true;
        }
    }
    /// <summary> shopï¿½Ì‚ï¿½ï¿½ï¿½ï¿½Èƒpï¿½ï¿½ï¿½[ï¿½{ï¿½^ï¿½ï¿½ï¿½ÅŒÄ‚Ñoï¿½ï¿½ </summary>
    public void FriendPowerLevelUp()
    {
        if (_addHeart._heart > 0)
        {
            //ï¿½}ï¿½Cï¿½iï¿½Xï¿½ï¿½ï¿½ï¿½Rï¿½Xï¿½g
            float cost;
            cost = _level * _friendPowerLevel;
            if (_addHeart._heart > cost)
            {
                _addHeart._heart -= cost;
                _friendPowerLevel += 1;
                //ï¿½Rï¿½Xï¿½gï¿½ï¿½1000ï¿½ğ’´‚ï¿½ï¿½ï¿½ï¿½ï¿½kï¿½Å•\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½ï¿½
                if (1000000 < _level * _friendPowerLevel)
                {
                    int kilo = (int)(_level * _friendPowerLevel) / 1000000;
                    _heartCost0.text = kilo + "m";
                }
                else if (1000 < _level * _friendPowerLevel)
                {
                    int kilo = (int)(_level * _friendPowerLevel) / 1000;
                    _heartCost0.text = kilo + "k";
                }
                else
                {
                    _heartCost0.text = (_level * _friendPowerLevel).ToString();
                }
            }
        }
    }
    /// <summary> shopï¿½Ì‚ï¿½ï¿½Ü‚ï¿½ï¿½Iï¿½[ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ÅŒÄ‚Ñoï¿½ï¿½ </summary>
    public void LovePowerLevelUp()
    {
        if (_addHeart._heart > 0)
        {
            //ï¿½}ï¿½Cï¿½iï¿½Xï¿½ï¿½ï¿½ï¿½Rï¿½Xï¿½g
            float cost;
            cost = _level * _lovePowerLevel;
            if (_addHeart._heart > cost)
            {
                _addHeart._heart -= cost;
                _lovePowerLevel += 1;
                _strokingAddHeart = _lovePowerLevel * 100;
                if (1000000 < _level * _lovePowerLevel)
                {
                    int kilo = (int)(_level * _lovePowerLevel) / 1000000;
                    _heartCost1.text = kilo + "m";
                }
                else if (1000 < _level * _lovePowerLevel)
                {
                    int kilo = (int)(_level * _lovePowerLevel) / 1000;
                    _heartCost1.text = kilo + "k";
                }
                else
                {
                    _heartCost1.text = (_level * _lovePowerLevel).ToString();
                }
                if (1000000 < _level * _strokingAddHeart)
                {
                    int kilo = (int)(_level * _strokingAddHeart) / 1000000;
                    _touchAddHeart.text = kilo + "m";
                }
                else if (1000 < _level * _strokingAddHeart)
                {
                    int kilo = (int)(_level * _strokingAddHeart) / 1000;
                    _touchAddHeart.text = kilo + "k";
                }
                else
                {
                    _touchAddHeart.text = (_level * _strokingAddHeart).ToString();
                }
            }
        }
    }
}
